name: Fetch

on: 
  workflow_dispatch:
    inputs:
      tahun:
        description: 'Tahun'
        required: true
        default: '2021'

jobs:
  fetcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - run: bash run.sh ${{ github.event.inputs.tahun }}
      - uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.TOKEN }}
